---
- hosts: win
  tasks:
    - name: Disable language hotkey for current users (adds new)
      ansible.windows.win_regedit:
        path: HKCU:\Keyboard Layout\Toggle
        name: Language Hotkey
        data: 3
        type: dword

    - name: Obtain the registry key's (Default) property
      ansible.windows.win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion
        name: ''
      register: current_version_default

    - name: Display reg key
      debug:
        var: current_version_defaul
